I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 94, in script
    return
Exception: Could not find return label (u'E:\\Users\\Nick\\Dropbox\\Writing\\VN\\TOA/game/chapters/chapter_2.rpy', 1471583208, 0).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 94, in script
    return
  File "E:\Users\Nick\Downloads\Programs\renpy-6.99.10-sdk\renpy\ast.py", line 1368, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "E:\Users\Nick\Downloads\Programs\renpy-6.99.10-sdk\renpy\execution.py", line 523, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'E:\\Users\\Nick\\Dropbox\\Writing\\VN\\TOA/game/chapters/chapter_2.rpy', 1471583208, 0).

Windows-7-6.1.7601-SP1
Ren'Py 6.99.10.1227
TOA 0.0
